name: NF7-DO-03 feature

on:
  push:
    branches:
      - 'feature/**'

jobs:
  check_conventionnal:
    name: conventional commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: webiny/action-conventional-commits@v1.0.5