name: NF7-DO-03 hotfix

on:
  push:
    branches:
      - 'hotfix/**'

jobs:
  check_conventional:
    name: conventional commits hotfix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: webiny/action-conventional-commits@v1.0.5