name: NF7-DO-03

on:
  pull_request:
    branches: [ dev ]

jobs:
  check_conventionnal:
    runs-on: ubuntu-latest
    steps:
      - name: checking
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: beemojs/conventional-pr-action@v2
        env:
          if: ${{ startsWith(github.head_ref, 'feature') }}
          run: echo "c'est commit conventionnal"